### ISSUE TITLE
Django backend setup

### ISSUE THREAD

**Issue by CodeConnoisseur74** [CodeConnoisseur74/the-win-manager#3]
title: 'Django backend setup'
labels: 'must have'
assignees: 'owner'

---

## Acceptance Criteria:

 - Django-admin setup and running successfully
 - Create 'users' app 
 - Create 'wins' app
 - Setup APIs

___
## Tasks:
 - [x] Django-admin setup
 - [x] Create 'users' app
 - [x] Create 'wins' app
 - [x] Setup APIs

**Comment by CodeConnoisseur74** [comment]
Created Django setup on main branch to test setup. Will continue by creating a setup branch for the 'users' and 'wins' apps.
